/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.aline;

public class App {

    public static void main(String[] args) {

        CPF cpf = new CPF("446.877.998-50");

        if(cpf.validar()){
            System.out.println("Válido");
        }
        else{
            System.out.println("Inválido");
        }
    }
}
